// 400 Motivational Quotes from Famous People
// Topics: Motivation, Work, Perseverance, Consistency, Discipline

export interface Quote {
    text: string;
    author: string;
}

export const motivationalQuotes: Quote[] = [
    // Motivation & Hard Work (1-50)
    { text: "Başarı tesadüf değildir. Sıkı çalışma, azim, öğrenme, fedakarlık ve en önemlisi yaptığınız işi sevmektir.", author: "Pelé" },
    { text: "Başarının sırrı, sıradan şeyleri olağanüstü iyi yapmaktır.", author: "John D. Rockefeller" },
    { text: "Gelecek, hayallerinin güzelliğine inananlarındır.", author: "Eleanor Roosevelt" },
    { text: "Yapabileceğinizi düşündüğünüz şey, başarınızı belirler.", author: "Henry Ford" },
    { text: "Başarı, cesaretini kaybetmeden başarısızlıktan başarısızlığa yürümektir.", author: "Winston Churchill" },
    { text: "Fırsatlar genellikle sıkı çalışma kılığına bürünür, bu yüzden çoğu insan onları tanımaz.", author: "Thomas Edison" },
    { text: "Dün geçmişti, yarın bir gizem, ama bugün bir hediyedir.", author: "Eleanor Roosevelt" },
    { text: "Büyük işler yapmanın tek yolu, yaptığınız işi sevmektir.", author: "Steve Jobs" },
    { text: "Hayatta en önemli şey başarısızlıklardan ders almaktır.", author: "Bill Gates" },
    { text: "Zayıf insanlar intikam alır, güçlü insanlar affeder, akıllı insanlar görmezden gelir.", author: "Albert Einstein" },
    { text: "Hayal gücü bilgiden daha önemlidir.", author: "Albert Einstein" },
    { text: "Her şey imkansız görünür, ta ki yapılana kadar.", author: "Nelson Mandela" },
    { text: "Asla pes etme. Bugünün zorluğu, yarının güzelliğinin habercisidir.", author: "Muhammad Ali" },
    { text: "Başarı son değildir, başarısızlık ölümcül değildir: Önemli olan devam etme cesaretidir.", author: "Winston Churchill" },
    { text: "İmkansız diye bir şey yoktur. Kelime bile 'Ben mümkünüm' diyor.", author: "Audrey Hepburn" },
    { text: "Düşmek başarısızlık değildir. Kalkmayı reddetmek başarısızlıktır.", author: "Mary Pickford" },
    { text: "Hayaller görmezseniz, asla gerçekliğiniz olmaz.", author: "Oprah Winfrey" },
    { text: "Kendinize inanın ve tüm yarışın yarısını kazandınız.", author: "Theodore Roosevelt" },
    { text: "Başarı, hazırlık fırsatla buluştuğunda ortaya çıkar.", author: "Bobby Unser" },
    { text: "Zor zamanlar güçlü insanları, güçlü insanlar kolay zamanları yaratır.", author: "G. Michael Hopf" },
    { text: "Yapamayacağınızı düşündüğünüz şeyi yapın.", author: "Eleanor Roosevelt" },
    { text: "Mükemmellik bir eylem değil, bir alışkanlıktır.", author: "Aristoteles" },
    { text: "Bugün yapmak istemediğin şey, yarın yapmak zorunda kalacağın şeydir.", author: "Benjamin Franklin" },
    { text: "Başarılı insanlar yapmaktan korktukları şeyleri yaparlar.", author: "Brian Tracy" },
    { text: "Her ustanın bir zamanlar acemi olduğunu unutma.", author: "Robin Sharma" },
    { text: "Engeller, hedeften gözünü ayırdığında gördüğün korkunç şeylerdir.", author: "Henry Ford" },
    { text: "Başarı yolunda acele etme, çünkü yavaş bir tempo daha az hata demektir.", author: "Byron Pulsifer" },
    { text: "Fırtınada dans etmeyi öğrenin, yağmur durduğunda alkışlarsınız.", author: "Vivian Greene" },
    { text: "Denemek başarısızlık değildir, hiç denememek başarısızlıktır.", author: "Wayne Gretzky" },
    { text: "Büyük hedefler koymak ve onlara ulaşmak için harekete geçmek bir yaşam şeklidir.", author: "Jim Rohn" },
    { text: "Başarısızlık, başarıya giden yolun sadece bir parçasıdır.", author: "Zig Ziglar" },
    { text: "Eğer bir rüyan varsa, onu korumak zorundasın.", author: "Chris Gardner" },
    { text: "Zor olan doğru, kolay olan yanlıştır.", author: "Jordan Peterson" },
    { text: "Disiplin, istediğin şeyi yapma özgürlüğünün anahtarıdır.", author: "Jocko Willink" },
    { text: "Gerçek değişim konforsuz bölgede başlar.", author: "Tony Robbins" },
    { text: "Hayat, beklenmedik zorlukları aşmakla ilgilidir.", author: "Richard Branson" },
    { text: "Hiçbir şey bir başarının tadına varamaz, şüphelerini yendiğin anda.", author: "Les Brown" },
    { text: "Kendi hikayenizin yazarı siz olun.", author: "Paulo Coelho" },
    { text: "Bugün zor, yarın daha zor, ama öbür gün güneşli olacak.", author: "Jack Ma" },
    { text: "En karanlık geceden sonra en parlak şafak doğar.", author: "Thomas Fuller" },
    { text: "Hayatınızın kontrolünü elinize almak, cesaretinizi kullanmaktır.", author: "Robin Sharma" },
    { text: "Başarı, en çok istediğiniz şey için, istediğiniz şeyi feda etmektir.", author: "Jeff Bezos" },
    { text: "Hayallerinizi gerçekleştirmek için uyanık olun.", author: "Muhammad Ali" },
    { text: "İnancınız kaderinizi belirler.", author: "Oprah Winfrey" },
    { text: "Potansiyelinizi kullanmadıkça hiçbir şey olmaz.", author: "Michael Jordan" },
    { text: "Farkındalık değişimin ilk adımıdır.", author: "Nathaniel Branden" },
    { text: "Kendinizi yenilemediğiniz gün, geride kaldığınız gündür.", author: "Satya Nadella" },
    { text: "Sadece hayal kurmak yetmez, harekete geçmek lazım.", author: "Walt Disney" },
    { text: "Başarısızlık, yeni bir strateji denemek için nedendir.", author: "Sam Walton" },
    { text: "İnandığınız her şeyi başarabilirsiniz.", author: "Napoleon Hill" },

    // Perseverance & Consistency (51-100)
    { text: "Azim, imkansızı mümkün, mümkünü olası ve olası olanı kesin yapar.", author: "Robert Half" },
    { text: "Tutarlılık, başarının en önemli bileşenidir.", author: "Dwayne Johnson" },
    { text: "Her şeyi bir kez yapmak yerine, bir şeyi bin kez yapın.", author: "Malcolm Gladwell" },
    { text: "Güç, fiziksel kapasiteden değil, yılmaz iradeden gelir.", author: "Mahatma Gandhi" },
    { text: "Kararlılık, her engeli aşar.", author: "Leonardo da Vinci" },
    { text: "En büyük zafer, asla pes etmemektir.", author: "Confucius" },
    { text: "Bir adım at, sonra bir adım daha. Yolculuk böyle tamamlanır.", author: "Lao Tzu" },
    { text: "Başarı, düştüğünüzde kaç kez kalktığınızla ölçülür.", author: "John D. Rockefeller" },
    { text: "Sabır acı olabilir, ancak meyvesi tatlıdır.", author: "Jean-Jacques Rousseau" },
    { text: "Zafer, en çok sebat edene aittir.", author: "Napoleon Bonaparte" },
    { text: "Küçük adımlar büyük sonuçlar doğurur.", author: "Robert Collier" },
    { text: "Her gün biraz daha ileri git.", author: "Bruce Lee" },
    { text: "Tek bir gece değil, binlerce gece uyumadan çalıştım.", author: "Nikola Tesla" },
    { text: "Düşenler değil, ayağa kalkamayanlar kaybeder.", author: "Jean Paul Sartre" },
    { text: "Başarı, düştükten sonra ayağa kalkma yeteneğidir.", author: "Vince Lombardi" },
    { text: "Büyük şeyler küçük adımlarla başlar.", author: "Mark Twain" },
    { text: "İrade gücü, en güçlü güçtür.", author: "Benjamin Franklin" },
    { text: "Her zorluğun içinde bir fırsat saklıdır.", author: "Albert Einstein" },
    { text: "Değişim zor olabilir, ama sabitlik seni yok eder.", author: "Jack Welch" },
    { text: "Kararlılık, engelleri fırsata dönüştürür.", author: "Theodore Roosevelt" },
    { text: "Kolay kazanılanı kaybetmek de kolaydır.", author: "Brian Tracy" },
    { text: "Sebat, başarının en güçlü silahıdır.", author: "Tim Ferriss" },
    { text: "Başarısızlık, yeniden denemek için bir fırsattır.", author: "Henry Ford" },
    { text: "Hedefine ulaşmak için, önce hedefe ulaştığını görmelisin.", author: "Zig Ziglar" },
    { text: "Yavaş ama kararlı her zaman kazanır.", author: "Ezop" },
    { text: "Başarı bir maraton, bir sprint değildir.", author: "Tim Grover" },
    { text: "Her başarısızlık, başarıya bir adım daha yaklaşmaktır.", author: "Thomas Edison" },
    { text: "Zor zamanlarda karakter belli olur.", author: "Martin Luther King Jr." },
    { text: "İnancınız sizi savaşmaya, azminiz ise kazanmaya götürür.", author: "Colin Powell" },
    { text: "Kararlı bir zihni hiçbir şey durduramaz.", author: "Og Mandino" },
    { text: "Büyük şeyler uzun vadeli düşünceden doğar.", author: "Jeff Bezos" },
    { text: "Başarı, sabır ve kararlılığın birleşimidir.", author: "Dolly Parton" },
    { text: "Zafer, pes etmeden bir dakika önce gelir.", author: "Napoleon Hill" },
    { text: "Her gün biraz daha iyi ol, her gün biraz daha güçlü.", author: "David Goggins" },
    { text: "Sabır tüm erdemlerin en büyüğüdür.", author: "Cato" },
    { text: "Büyük işler, küçük işlerin sürekliliğinden doğar.", author: "Vincent Van Gogh" },
    { text: "Her şey pratikle gelir, deha bile.", author: "Pablo Picasso" },
    { text: "Kararlılık, yeteneksizliği bile yenebilir.", author: "Tony Dungy" },
    { text: "İmkansız görünen şey bugün tamamlanır, mucizeler biraz daha uzun sürer.", author: "US Army Corps of Engineers" },
    { text: "Koşullar asla mükemmel olmayacak. Şimdi başla.", author: "Napoleon Hill" },
    { text: "Başarısızlık sadece geçicidir. Pes etmek onu kalıcı yapar.", author: "Marilyn vos Savant" },
    { text: "Her gün biraz daha öğren, biraz daha büyü.", author: "Warren Buffett" },
    { text: "Hayat döngüsündür, düştüğünde kalkacak güce sahip ol.", author: "Rocky Balboa (Film)" },
    { text: "Süreklilik, dâhilik kadar güçlüdür.", author: "Ovid" },
    { text: "Uzun vadeli düşünmek, kısa vadeli acıya katlanmaktır.", author: "Ray Dalio" },
    { text: "Her sabah yeniden doğarsın. Ne yapacağın sana bağlı.", author: "Dalai Lama" },
    { text: "Sadece bir adım daha. Her zaman sadece bir adım daha.", author: "David Goggins" },
    { text: "Derin köklere sahip ağaçlar, en güçlü fırtınalardan korkmaz.", author: "Japon Atasözü" },
    { text: "Yolculuk bin adımla başlar, ama ilk adım en önemlisidir.", author: "Lao Tzu" },
    { text: "Engeller, rota değil, sadece güzergâh değişikliğidir.", author: "Marcus Aurelius" },

    // Discipline & Self-Control (101-150)
    { text: "Disiplin, olmak istediğin kişi ile şu an olduğun kişi arasındaki köprüdür.", author: "Jim Rohn" },
    { text: "Disiplin acıdır ama ödülü sonsuzdur.", author: "Jocko Willink" },
    { text: "Özgürlük, disiplin ile gelir.", author: "Aristoteles" },
    { text: "Kendini yönetemeyen, başkalarını yönetemez.", author: "Sun Tzu" },
    { text: "Erken kalkmak, günü kazanmaktır.", author: "Benjamin Franklin" },
    { text: "Plansız bir hedef sadece bir dilektir.", author: "Antoine de Saint-Exupéry" },
    { text: "Alışkanlıklar kaderi belirler.", author: "Jack Canfield" },
    { text: "Küçük eylemler, büyük sonuçlar yaratır.", author: "Robert Maurer" },
    { text: "Disiplin, motivasyon sona erdiğinde devreye girer.", author: "Jim Rohn" },
    { text: "Her gün, dün durduğun yerden devam et.", author: "Walt Disney" },
    { text: "En büyük zafer, kendini yenmektir.", author: "Plato" },
    { text: "Güçlü olmak için önce disiplinli olmak gerekir.", author: "Arnold Schwarzenegger" },
    { text: "İrade kasları gibi, egzersizle güçlenir.", author: "Kelly McGonigal" },
    { text: "Kendine söz ver ve o sözü tut.", author: "Tony Robbins" },
    { text: "İstikrar, başarının anasıdır.", author: "Eric Thomas" },
    { text: "Her gün aynı saatte kalkın, disiplin oluşur.", author: "Jocko Willink" },
    { text: "Başarı, günlük alışkanlıkların toplamıdır.", author: "John C. Maxwell" },
    { text: "Disiplin, istediğini elde etmenin tek yoludur.", author: "David Goggins" },
    { text: "Konfor alanınızın dışına çıkmadan büyüyemezsiniz.", author: "Brian Tracy" },
    { text: "Her gün biraz zor, sonsuza kadar kolay.", author: "Les Brown" },
    { text: "Sıkı çalışma dışında başarıya giden kısayol yoktur.", author: "Kobe Bryant" },
    { text: "Güçlü bir zihin, güçlü bir vücut oluşturur.", author: "Mike Tyson" },
    { text: "Düşüncelerin sözlerine, sözlerin eylemlerine, eylemlerin alışkanlıklarına dönüşür.", author: "Mahatma Gandhi" },
    { text: "Önce alışkanlıkları biz oluştururuz, sonra alışkanlıklar bizi.", author: "John Dryden" },
    { text: "Zamanı kontrol eden, hayatı kontrol eder.", author: "Brian Tracy" },
    { text: "Erteleme, başarının en büyük düşmanıdır.", author: "Abraham Lincoln" },
    { text: "Küçük şeylerde disiplin, büyük şeylerde başarı getirir.", author: "George Leonard" },
    { text: "İrade, karakterin soluğudur.", author: "William Penn" },
    { text: "Başarılı olmak için sabırlı olmak gerekir.", author: "Jeff Bezos" },
    { text: "Her günü bir başyapıt gibi yap.", author: "John Wooden" },
    { text: "Disiplin, özgürlüğe giden yoldur.", author: "Jocko Willink" },
    { text: "Her zor şey başarıldığında, daha güçlü olursun.", author: "Ryan Holiday" },
    { text: "Hedefin büyük olsun, ama adımların küçük.", author: "Tony Robbins" },
    { text: "Sıkı çalış, sessiz kal. Başarın seni konuştursun.", author: "Arnold Schwarzenegger" },
    { text: "Her karar birikir. Akıllıca seç.", author: "Gary Vaynerchuk" },
    { text: "Zihin, eğitilmiş bir kas gibidir.", author: "Carol Dweck" },
    { text: "Sabahları erken kalk, gece erken yat. Disiplin başlar.", author: "Robin Sharma" },
    { text: "Her gün %1 daha iyi ol.", author: "James Clear" },
    { text: "Disiplinsiz bir hayat, kaosa davetiyedir.", author: "Jocko Willink" },
    { text: "Eylem her şeyi yener.", author: "Gary Vaynerchuk" },
    { text: "Her gün bir önceki günden daha iyi ol.", author: "Dwayne Johnson" },
    { text: "Zor seçimler kolay hayat, kolay seçimler zor hayat.", author: "Jerzy Gregorek" },
    { text: "Elinden gelenin en iyisini yap, gerisini bırak.", author: "Dalai Lama" },
    { text: "Önce kendinize yatırım yapın.", author: "Warren Buffett" },
    { text: "En büyük hata pes etmektir.", author: "Confucius" },
    { text: "Konforlu olmaktan kaçın, büyüme ordadır.", author: "Ray Dalio" },
    { text: "Hayatını düzene sok, kaos ortadan kalkar.", author: "Jordan Peterson" },
    { text: "Disiplin, düşmanı değil dosttur.", author: "Jocko Willink" },
    { text: "Proaktif ol, reaktif değil.", author: "Stephen Covey" },
    { text: "Her gün bir kitap oku, beyni besle.", author: "Warren Buffett" },

    // Success & Achievement (151-200)
    { text: "Başarı, tutku ve azmin birleşimidir.", author: "Angela Duckworth" },
    { text: "Büyük başarılar, büyük riskler gerektirir.", author: "Mark Zuckerberg" },
    { text: "Başarı, aklındakini gerçeğe dönüştürmektir.", author: "Elon Musk" },
    { text: "Sınırlarınızı test etmezseniz, sınırlarınızı bilemezsiniz.", author: "Richard Branson" },
    { text: "Başarılı insanlar normal insanların yapmadığını yapar.", author: "Jim Rohn" },
    { text: "Başarı, fırsatı görme yeteneğidir.", author: "Bill Gates" },
    { text: "Harika şeyler yapmak için harika hayallere ihtiyacınız var.", author: "Elon Musk" },
    { text: "Başarıya giden yol, başarısızlıklarla döşelidir.", author: "Michael Jordan" },
    { text: "Hayallerine ulaşmak için uyanık ol.", author: "Les Brown" },
    { text: "Başarı, şansa değil seçimlere bağlıdır.", author: "Denzel Washington" },
    { text: "Harekete geçmeden hayal kurmak hayaldir.", author: "Colin Powell" },
    { text: "Başarı bir yolculuktur, bir varış noktası değil.", author: "Zig Ziglar" },
    { text: "Yapabileceğinizi düşünürseniz, zaten yarı yoldasınız.", author: "Theodore Roosevelt" },
    { text: "Büyük işler yapmak istiyorsan, büyük fedakarlıklar yap.", author: "Michael Phelps" },
    { text: "Başarılı olmak için başarılı gibi düşün.", author: "Napoleon Hill" },
    { text: "Kendin ol, başkaları zaten alınmış.", author: "Oscar Wilde" },
    { text: "Başarı, küçük işlerin mükemmelliğinden doğar.", author: "Steve Jobs" },
    { text: "Hayaller gerçek olabilir, eğer yeterince istersen.", author: "Walt Disney" },
    { text: "Büyük işler yapmak için küçük egolardan vazgeç.", author: "Tim Cook" },
    { text: "Başarı, sabırla kazanılır.", author: "Bill Gates" },
    { text: "Zor işlerde tek fark, devam etmektir.", author: "Vince Lombardi" },
    { text: "Başarı, beklentilerin ötesine geçmektir.", author: "Elon Musk" },
    { text: "İnandığınız şeyi yapın, başarı gelir.", author: "Oprah Winfrey" },
    { text: "Başarı, açgözlülükle değil, cömertlikle gelir.", author: "Richard Branson" },
    { text: "Hayat, sizin onu yaptığınız şeydir.", author: "Oprah Winfrey" },
    { text: "Başarı, eyleme geçmektir.", author: "Tony Robbins" },
    { text: "Başarılı olmak istiyorsan, önce yardım et.", author: "Zig Ziglar" },
    { text: "Başarı, planlamadan gelir.", author: "Peter Drucker" },
    { text: "Yükselmek için hizmet et.", author: "Martin Luther King Jr." },
    { text: "Başarı, değer yaratmaktır.", author: "Jeff Bezos" },
    { text: "Başarı, azim ve adanmışlık gerektirir.", author: "Serena Williams" },
    { text: "Yetenek yalnız başına yetmez, çalışmak gerekir.", author: "Cristiano Ronaldo" },
    { text: "Başarı, kendini sürekli geliştirmektir.", author: "Satya Nadella" },
    { text: "Başarı, doğru kararlar almaktır.", author: "Ray Dalio" },
    { text: "Hayaller büyükse, engeller küçülür.", author: "Jack Ma" },
    { text: "İnancınız sizi başarıya taşır.", author: "Muhammad Ali" },
    { text: "Büyük hedefler, büyük sonuçlar getirir.", author: "Grant Cardone" },
    { text: "Başarı, öğrenmeyi bırakmamaktır.", author: "Warren Buffett" },
    { text: "Hayatı yaşa, seyrederek geçirme.", author: "Gary Vaynerchuk" },
    { text: "Başarı, eylemde yatar.", author: "Pablo Picasso" },
    { text: "Başarının sırrı, sırrı aramayı bırakmaktır.", author: "Deepak Chopra" },
    { text: "Başarı, fedakarlığın karşılığıdır.", author: "Kobe Bryant" },
    { text: "Hayal et, inan, başar.", author: "Walt Disney" },
    { text: "Başarı, odaklanmayı gerektirir.", author: "Bill Gates" },
    { text: "Başarıya giden yol tutarlılıktır.", author: "Dwayne Johnson" },
    { text: "Hayatta sadece bir kez yaşarsın, en iyisini yap.", author: "Steve Jobs" },
    { text: "Başarı zor kazanılır, kolay kaybedilir.", author: "Sam Walton" },
    { text: "Başarı, konfor alanından çıkmaktır.", author: "Brian Tracy" },
    { text: "Başarı, eylemsiz olmaz.", author: "Gary Vaynerchuk" },
    { text: "Başarı, doğru insanlarla çalışmaktır.", author: "Tim Ferriss" },

    // Mindset & Attitude (201-250)
    { text: "Zihin, kendine söylediğiniz her şeye inanır.", author: "Marisa Peer" },
    { text: "Bakış açınız, hayatınızın kalitesini belirler.", author: "Wayne Dyer" },
    { text: "Düşünceleriniz, kaderinizi şekillendirir.", author: "Marcus Aurelius" },
    { text: "Olumlu düşünce, olumlu sonuçlar doğurur.", author: "Norman Vincent Peale" },
    { text: "Zihninizi değiştirin, hayatınızı değiştirin.", author: "Tony Robbins" },
    { text: "Her şey zihinden başlar.", author: "Buddha" },
    { text: "Korku, sadece zihinde var olur.", author: "Mahatma Gandhi" },
    { text: "Tutum her şeydir.", author: "Charles Swindoll" },
    { text: "Zihniniz bir bahçedir, ne ekerseniz onu biçersiniz.", author: "Earl Nightingale" },
    { text: "Öğrenme, değişimin başlangıcıdır.", author: "Jim Rohn" },
    { text: "Korkularınız, önünüzdeki engeller değildir.", author: "Michael Jordan" },
    { text: "Zihin, güçlü olduğunda vücut takip eder.", author: "Arnold Schwarzenegger" },
    { text: "Her şey tutumla başlar.", author: "Lou Holtz" },
    { text: "Düşünceleriniz gerçekliğinizi yaratır.", author: "Rhonda Byrne" },
    { text: "Pozitif bir zihin, pozitif bir yaşam.", author: "Dalai Lama" },
    { text: "Düşmek yenilgi değil, kalkmamak yenilgidir.", author: "Zig Ziglar" },
    { text: "İnanmak başarmanın yarısıdır.", author: "Theodore Roosevelt" },
    { text: "Önce düşün, sonra hareket et.", author: "Sun Tzu" },
    { text: "Başarı beyinde başlar.", author: "David Goggins" },
    { text: "Siz, düşüncelerinizin ürünüsünüz.", author: "Mahatma Gandhi" },
    { text: "Şikâyet etmek yerine çözüm üret.", author: "Gary Vaynerchuk" },
    { text: "Her zorluk, bir fırsat taşır.", author: "John F. Kennedy" },
    { text: "Başarısızlık, tutumda yatar.", author: "Henry Ford" },
    { text: "Hayatınızın yönetmeni siz olun.", author: "Tim Ferriss" },
    { text: "Her şey olumlu bir bakış açısıyla başlar.", author: "Oprah Winfrey" },
    { text: "Zihniniz en güçlü silahınızdır.", author: "David Goggins" },
    { text: "Düşünceleriniz sözlerinizi şekillendirir.", author: "Lao Tzu" },
    { text: "Kolay yolu seçme, doğru yolu seç.", author: "Jordan Peterson" },
    { text: "Zor zamanlar karakteri ortaya çıkarır.", author: "John Wooden" },
    { text: "Her sabah bir seçimdir. Doğru seçimi yap.", author: "Hal Elrod" },
    { text: "Sınırlarınız, inançlarınızdır.", author: "Tony Robbins" },
    { text: "Olumsuzluğu bırakın, olumluluğu kucaklayın.", author: "Wayne Dyer" },
    { text: "İnsan, düşündüğü şey olur.", author: "Earl Nightingale" },
    { text: "Zihnin gücünü asla küçümseme.", author: "Bruce Lee" },
    { text: "Her düşünce bir tohumdur.", author: "Louise Hay" },
    { text: "Tutum, başarının temelidir.", author: "Zig Ziglar" },
    { text: "Her gün yeni bir başlangıçtır.", author: "Eleanor Roosevelt" },
    { text: "Başarı, zihinsel olarak hazır olmaktır.", author: "Michael Phelps" },
    { text: "Zihniniz kapılarını açın, fırsatlar gelsin.", author: "Deepak Chopra" },
    { text: "Düşüncelerinizi kontrol edin, hayatınızı kontrol edin.", author: "Napoleon Hill" },
    { text: "Her zorluk, bir öğretmendir.", author: "Ryan Holiday" },
    { text: "Hayata bakış açınızı değiştirin, hayatınız değişsin.", author: "Oprah Winfrey" },
    { text: "Zihin, egzersiz ile güçlenir.", author: "Carol Dweck" },
    { text: "Her problem bir çözüm taşır.", author: "Tony Robbins" },
    { text: "Başarı, zihinsel dayanıklılık gerektirir.", author: "Angela Duckworth" },
    { text: "Sizin düşünceleriniz, sizin hayatınız.", author: "James Allen" },
    { text: "Olumlu düşünmek bir seçimdir.", author: "Norman Vincent Peale" },
    { text: "Her düşünce bir eylem doğurur.", author: "Buddha" },
    { text: "Kayıpları kabul et, kazançlara odaklan.", author: "Ray Dalio" },
    { text: "Büyüme zihniyeti, başarı zihniyetidir.", author: "Carol Dweck" },

    // Work Ethic & Productivity (251-300)
    { text: "Sıkı çalışan herkes başarılı olmaz, ama başarılı olan herkes sıkı çalışır.", author: "Kobe Bryant" },
    { text: "Üretkenlik, doğru şeylere odaklanmaktır.", author: "Tim Ferriss" },
    { text: "Zaman, en değerli kaynaktır.", author: "Peter Drucker" },
    { text: "Önceliklerinizi belirleyin ve takip edin.", author: "Stephen Covey" },
    { text: "Yaptığınız işe tutkuyla bağlanın.", author: "Steve Jobs" },
    { text: "İşinizi sevmek, başarının ilk şartıdır.", author: "Richard Branson" },
    { text: "Her gün bir adım daha ileriye gidin.", author: "Gary Vaynerchuk" },
    { text: "Odak, başarının anahtarıdır.", author: "Bill Gates" },
    { text: "Planlayın, uygulayın, kazanın.", author: "Zig Ziglar" },
    { text: "Her dakika önemli, israf etmeyin.", author: "Benjamin Franklin" },
    { text: "Verimlilik, akıllıca çalışmaktır.", author: "Tim Ferriss" },
    { text: "Başarılı insanlar vaktini boşa harcamaz.", author: "Jeff Bezos" },
    { text: "Sürekli ilerleme, mükemmellikten iyidir.", author: "Mark Twain" },
    { text: "Küçük işleri mükemmel yapın.", author: "Ray Kroc" },
    { text: "Bugün yapmamak, yarına yük bırakmaktır.", author: "Benjamin Franklin" },
    { text: "Başarı rutinlerde gizlidir.", author: "John C. Maxwell" },
    { text: "Her sabah bir amaçla uyanın.", author: "Simon Sinek" },
    { text: "Çalışma yoğunluğu kadar kalitesi de önemlidir.", author: "Cal Newport" },
    { text: "Zor işler sizi büyütür.", author: "David Goggins" },
    { text: "Eylem planını uygulayın, sonuçları göreceksiniz.", author: "Tony Robbins" },
    { text: "Her gün bir şeyler öğrenin.", author: "Warren Buffett" },
    { text: "Yapılacaklar listesi olmadan başarı olmaz.", author: "Brian Tracy" },
    { text: "Verimli olmak, meşgul olmaktan farklıdır.", author: "Tim Ferriss" },
    { text: "Başarılı insanlar erken kalkar.", author: "Robin Sharma" },
    { text: "Konsantre olun, daha az ile daha fazla yapın.", author: "Greg McKeown" },
    { text: "Hedefe giden yolda her adım önemlidir.", author: "Zig Ziglar" },
    { text: "Zor işler, büyük insanları yaratır.", author: "William A. Ward" },
    { text: "Vakit nakittir, akıllıca harca.", author: "Benjamin Franklin" },
    { text: "Başarılı insanlar sistematik çalışır.", author: "John Wooden" },
    { text: "Her gün sabah rutninizi yapın.", author: "Hal Elrod" },
    { text: "Odaklanmak en önemli beceridir.", author: "Cal Newport" },
    { text: "Derin çalışma, üstün sonuçlar getirir.", author: "Cal Newport" },
    { text: "Zamanı yönetmek, hayatı yönetmektir.", author: "Brian Tracy" },
    { text: "Verimli bir gün için plan yapın.", author: "Peter Drucker" },
    { text: "Her iş için en iyisini verin.", author: "Kobe Bryant" },
    { text: "Başarılı insanlar erteleme yapmaz.", author: "Brian Tracy" },
    { text: "Hayatınızı planlayın, planınızı yaşayın.", author: "Zig Ziglar" },
    { text: "Küçük şeyler büyük farklar yaratır.", author: "John Wooden" },
    { text: "Çalışmak şansa bırakılamaz.", author: "Gary Player" },
    { text: "Tutarlılık, dâhilik kadar önemlidir.", author: "Dwayne Johnson" },
    { text: "Verimlilik, hayatın kalitesini belirler.", author: "Cal Newport" },
    { text: "Her gün kendinizi zorlayın.", author: "David Goggins" },
    { text: "Başarı, sürekli eyleme geçmektir.", author: "Tony Robbins" },
    { text: "Hedefler olmadan planlama anlamsızdır.", author: "Peter Drucker" },
    { text: "Konsantrasyon, sonuç getirir.", author: "Bill Gates" },
    { text: "Her gecede ertesi günü planla.", author: "Brian Tracy" },
    { text: "İşlerinize öncelik verin.", author: "Stephen Covey" },
    { text: "Sistematik çalışma, sistematik başarı getirir.", author: "Jim Rohn" },
    { text: "Çok çalışmak yerine akıllı çalış.", author: "Tim Ferriss" },
    { text: "Zamanınızı en iyi şekilde kullanın.", author: "Benjamin Franklin" },

    // Courage & Determination (301-350)
    { text: "Cesaret, korkunun yokluğu değil, korkuya rağmen hareket etmektir.", author: "Nelson Mandela" },
    { text: "Korku sadece zihinde var, gerçekte değil.", author: "Dalai Lama" },
    { text: "Cesaretiniz, korkunuzun önünde olmalı.", author: "Oprah Winfrey" },
    { text: "Risk almazsanız, asla kazanamazsınız.", author: "Mark Zuckerberg" },
    { text: "Cesaret, zor şeyleri kolay yapma gücüdür.", author: "John Wayne" },
    { text: "Büyük hayaller cesaret ister.", author: "Elon Musk" },
    { text: "Korkuya rağmen ilerleyin.", author: "Susan Jeffers" },
    { text: "Başarı için cesaret şarttır.", author: "Winston Churchill" },
    { text: "Korku, sizi durdurmak için bir araçtır.", author: "Tony Robbins" },
    { text: "Başarısızlık korkusu, başarısızlığın kendisidir.", author: "Seth Godin" },
    { text: "Cesaret olmadan büyük şeyler olmaz.", author: "Maya Angelou" },
    { text: "Korkularınızla yüzleşin ve büyüyün.", author: "Eleanor Roosevelt" },
    { text: "Büyük sonuçlar cesur kararlar gerektirir.", author: "Richard Branson" },
    { text: "Korku, sadece bir duygudur.", author: "David Goggins" },
    { text: "Cesaret, karakterin omurgasıdır.", author: "Aristotle" },
    { text: "Riskler, fırsatların kapılarını açar.", author: "Jeff Bezos" },
    { text: "Korkunuz sizi tanımlamasın.", author: "Les Brown" },
    { text: "Başlamak cesaret gerektirir.", author: "Walt Disney" },
    { text: "Her büyük başarı, küçük bir cesaretle başlar.", author: "Martin Luther King Jr." },
    { text: "Cesaret, günlük bir seçimdir.", author: "Brené Brown" },
    { text: "Korku, başarının düşmanıdır.", author: "Og Mandino" },
    { text: "Cesaret, imkânsızı mümkün yapar.", author: "Muhammad Ali" },
    { text: "Korkunuzu kucaklayın, sizi büyütür.", author: "Tony Robbins" },
    { text: "Cesur olun, başarı sizi bekliyor.", author: "Grant Cardone" },
    { text: "Korku, sadece bir hayaldir.", author: "Wayne Dyer" },
    { text: "Cesaret, her şeyin başlangıcıdır.", author: "Plato" },
    { text: "Korkudan kaçma, korkuyla dans et.", author: "Susan Jeffers" },
    { text: "Hayalleriniz için savaşın.", author: "Paulo Coelho" },
    { text: "Cesaret, zayıflığın tersidir.", author: "Brené Brown" },
    { text: "Başarısızlık korkusu, başarıyı engeller.", author: "Denzel Washington" },
    { text: "Korku varsa, cesaret de var demektir.", author: "Nelson Mandela" },
    { text: "Cesaretle yola çık, korku geride kalır.", author: "Robin Sharma" },
    { text: "Büyük işler cesur yürekler ister.", author: "Mark Twain" },
    { text: "Korkusuz olmak değil, korkuya rağmen olmak önemlidir.", author: "Brené Brown" },
    { text: "Cesaret, her gün yeniden kazanılır.", author: "David Goggins" },
    { text: "Korkunuzun ötesine geçin, özgürlük orada.", author: "Nelson Mandela" },
    { text: "Cesaretli adımlar, büyük sonuçlar getirir.", author: "Elon Musk" },
    { text: "Korku, sadece bir engeldir, geçin.", author: "Tony Robbins" },
    { text: "Cesaret, başarının anahtarıdır.", author: "Winston Churchill" },
    { text: "Korkunun üstesinden gelin, güç burada yatar.", author: "Mark Victor Hansen" },
    { text: "Büyük işler yapmak için cesaret şarttır.", author: "Teddy Roosevelt" },
    { text: "Korku, sadece bir düşüncedir.", author: "Buddha" },
    { text: "Cesaret, karanlıkta ilk adımı atmaktır.", author: "Martin Luther King Jr." },
    { text: "Korkunuz ne kadar büyükse, büyüme potansiyeliniz o kadar büyük.", author: "Robin Sharma" },
    { text: "Cesaret, hayatı değiştirir.", author: "Brené Brown" },
    { text: "Her adım cesaret gerektirir.", author: "Les Brown" },
    { text: "Korkularınızın efendisi olun.", author: "Tony Robbins" },
    { text: "Cesaret, zaferin temelidir.", author: "Sun Tzu" },
    { text: "Korku, sadece bir uyarıdır, engel değil.", author: "Gary Vaynerchuk" },
    { text: "Cesaret, her gün yeniden seçilir.", author: "David Goggins" },

    // Health & Fitness (351-400)
    { text: "Vücut bir tapınaktır, ona iyi bakın.", author: "Astrid Alauda" },
    { text: "Sağlık, en büyük servettir.", author: "Dalai Lama" },
    { text: "Fiziksel güç, zihinsel gücü destekler.", author: "Arnold Schwarzenegger" },
    { text: "Bedeniniz, yaşadığınız tek evdir.", author: "Jim Rohn" },
    { text: "Sağlıklı bir vücut, sağlıklı bir zihin demektir.", author: "Thales" },
    { text: "Egzersiz, beyine ilaçtır.", author: "John Ratey" },
    { text: "Hareket et ya da pas tut.", author: "Jim Rohn" },
    { text: "Her gün bir adım, sağlığa ulaştırır.", author: "Hippocrates" },
    { text: "Sağlık, kendi kendine bakım gerektirir.", author: "Louise Hay" },
    { text: "Güçlü bir beden, güçlü bir irade ile gelir.", author: "Mahatma Gandhi" },
    { text: "Fiziksel aktivite, mutluluğun anahtarıdır.", author: "Richard Branson" },
    { text: "Sağlık olmadan başarı anlamsızdır.", author: "Robin Sharma" },
    { text: "Bedeninizi eğitin, zihniniz takip edecektir.", author: "Jocko Willink" },
    { text: "Her gün biraz egzersiz, hayatı değiştirir.", author: "Michelle Obama" },
    { text: "Sağlık, günlük seçimlerin toplamıdır.", author: "Dr. Mark Hyman" },
    { text: "Spor, strese en iyi ilaçtır.", author: "Elle Macpherson" },
    { text: "Bedeninizi ihmal etmeyin, zamanla cezasını çekersiniz.", author: "Jim Rohn" },
    { text: "Fitness, hayatın kalitesini artırır.", author: "Jack LaLanne" },
    { text: "Güçlü ol, fiziksel olarak güçlü ol.", author: "Jocko Willink" },
    { text: "Her sabah egzersizle başlayın.", author: "Tony Robbins" },
    { text: "Sağlıklı beslenme, sağlıklı yaşamın temelidir.", author: "Ann Wigmore" },
    { text: "Bedeninizi bir makine gibi bakın.", author: "Arnold Schwarzenegger" },
    { text: "Fiziksel güç, zihinsel gücü besler.", author: "David Goggins" },
    { text: "Egzersiz, enerjinin kaynağıdır.", author: "Richard Branson" },
    { text: "Sağlık, azim ile korunur.", author: "Hippocrates" },
    { text: "Vücudu eğitmek, zihni eğitmektir.", author: "Plato" },
    { text: "Her gün biraz spor yapın.", author: "Michelle Obama" },
    { text: "Fiziksel güç, iç gücü artırır.", author: "Arnold Schwarzenegger" },
    { text: "Sağlığınıza yatırım yapın.", author: "Robin Sharma" },
    { text: "Egzersiz, hayatın en iyi ilacıdır.", author: "Frank Sonnenberg" },
    { text: "Bedeninizi zorlamadan, büyüyemezsiniz.", author: "David Goggins" },
    { text: "Sağlık, en değerli hazinedir.", author: "Buddha" },
    { text: "Fiziksel aktivite, zihinsel berraklık sağlar.", author: "John F. Kennedy" },
    { text: "Sağlığınız, önceliğiniz olmalı.", author: "Tony Robbins" },
    { text: "Egzersiz, özgüvenin anahtarıdır.", author: "Elle Macpherson" },
    { text: "Güçlü bir vücut, güçlü bir irade ile başlar.", author: "Arnold Schwarzenegger" },
    { text: "Sağlıksız bir beden, sağlıksız bir yaşam demektir.", author: "Hippocrates" },
    { text: "Fiziksel güç, her şeyin başlangıcıdır.", author: "Jocko Willink" },
    { text: "Egzersiz yapmak, kendinize saygı duymaktır.", author: "Oprah Winfrey" },
    { text: "Bedeninize saygı gösterin, size hizmet edecektir.", author: "Astrid Alauda" },
    { text: "Sağlık, günlük seçimlerinizle belirlenir.", author: "Deepak Chopra" },
    { text: "Fiziksel aktivite, beyni güçlendirir.", author: "John Ratey" },
    { text: "Her gün bir adım daha güçlü.", author: "David Goggins" },
    { text: "Sağlık, herkesin hakkıdır.", author: "World Health Organization" },
    { text: "Egzersiz yapmak, geleceğe yatırımdır.", author: "Jack LaLanne" },
    { text: "Bedeninizi iyi besleyin, iyi çalışır.", author: "Ann Wigmore" },
    { text: "Güçlü ol, sağlıklı ol, mutlu ol.", author: "Arnold Schwarzenegger" },
    { text: "Sağlık, en büyük zenginliktir.", author: "Virgil" },
    { text: "Fiziksel güç, ruh gücünü artırır.", author: "Dalai Lama" },
    { text: "Her gün, sağlığınıza bir yatırım yapın.", author: "Robin Sharma" },
];

/**
 * Günün tarihine göre aynı sözü döndürür.
 * Sunucu tarihine göre söz seçer (kullanıcı lokal saatini değiştirse bile etkilenmez).
 * @param dateKey - Server date in YYYY-MM-DD format
 */
export const getDailyQuote = (dateKey: string): Quote => {
    // Extract year and calculate day of year from dateKey
    const [year, month, day] = dateKey.split('-').map(Number);
    const date = new Date(year, month - 1, day);
    const startOfYear = new Date(year, 0, 1);
    const diff = date.getTime() - startOfYear.getTime();
    const oneDay = 1000 * 60 * 60 * 24;
    const dayOfYear = Math.floor(diff / oneDay) + 1;

    const index = dayOfYear % motivationalQuotes.length;
    console.log(`📜 [Quote] Server date: ${dateKey}, Day of year: ${dayOfYear}, Quote index: ${index}`);
    return motivationalQuotes[index];
};

/**
 * Rastgele bir söz döndürür.
 */
export const getRandomQuote = (): Quote => {
    const index = Math.floor(Math.random() * motivationalQuotes.length);
    return motivationalQuotes[index];
};
